### ISSUE TITLE
Nota

### ISSUE THREAD

**Issue by ioliasa** [FzrFernando/ProgramacionJava#3]
En el constructor si quieres que la fecha de creación sea igual que la de modificación, asinga la fecha de creación a la de modifcación porque si no, cambiará unos segundo.
No puedes cambiar los nombres de los métodos, por ejemplo getFechaUltimaModificacion debe ser getFechaModificacion
En isCreadoAnterior y en isModificadoAnterior tienes que comprobar que el parámetro no sea nulo.

**Comment by FzrFernando** [comment]
Tanto lo del constructor como lo de los nombres de los métodos están corregidos, no estoy seguro de si valdría la opción que he puesto para comprobar que no sea nulo, dejo abierto el issue hasta la confirmación.

**Comment by ioliasa** [comment]
Te lo dejo abierto y mañana lo vemos en clase

**Comment by FzrFernando** [comment]
Corregido en clase

**Comment by ioliasa** [comment]
Esto "En isCreadoAnterior y en isModificadoAnterior tienes que comprobar que el parámetro no sea nulo." sigue estando mal.
