### ISSUE TITLE
NotaAlarma

### ISSUE THREAD

**Issue by ioliasa** [FzrFernando/ProgramacionJava#4]
Tienes que terminar notaAlarma (es para tener controlado que te falta)

**Comment by FzrFernando** [comment]
Inma con esta clase tenía dudas, pero como me había quedado rezagado porque estuve pendiente de otros exámenes pues se me olvidaba preguntar, y mi duda es que al constructor le pasas un String, pero en esa clase no hay ninguno, se refiere a String texto del padre no?

**Comment by ioliasa** [comment]
Exactamente, lo primero que tienes que hacer es llamar al constructor del padre con el super, y le pasas el texto que necesita para crear la nota padre

**Comment by FzrFernando** [comment]
Corregido en clase
